---
title: "F1-API-Setup"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
      version: 3
---
```{r API-Setup, include=false}
source("F1-API-Setup.r")
```
# Filtering down to just Race Sessions in the Year  2025 and all time sessions
```{r Filter-Sessions}
##I am creating a new dataframe that 2025-filters the session_data dataframe, isolating just the session type and the year
race_sessions_2025 <- dplyr::filter(session_data, session_name == "Race", year == 2025)
race_sessions <- dplyr::filter(session_data, session_name == "Race")
```

```{r Fix-BOR&BEA-Issues}
# Remove BOR from session 9223 since it is broken
driver_names <- driver_names %>%
  filter(!(name_acronym == "BOR" & session_key == 9223))
  filter(!(name_acronym == "BEA" & driver_number %in% c(38, 50)))
#driver_names <- filter
```

# Finding the Unique IDs for all Race Sessions I have data for
```{r Unique-Session-IDs}
unique_race_session_ids <- unique(race_sessions$session_key)
```
# Then I am filtering the pitstop data to only include pitstops from those sessions
```{r Pitstop-Race-Only}
pitstop_race_only <- dplyr::filter(pitstop_data, session_key %in% unique_race_session_ids)

#Now I am going to filter the data down to pitstops under 60 seconds, and I will call anything longer than that a DNF

pitstop_race_only <- pitstop_race_only %>% 
  mutate(is_dnf = pit_duration >= 60) %>%
  mutate(pit_duration_clean = ifelse(pit_duration >= 60, NA, pit_duration))
```
# I am going to create a graph of all pitstops that I have data for, breaking it down by driver and calculating the average pitstop length
```{r Average-Pit}
pitstop_averages <- pitstop_race_only %>%
  group_by(driver_number) %>%
  summarise(average_pitstop_time = mean(pit_duration_clean, na.rm = TRUE)) %>%
  arrange(average_pitstop_time)
```

```{r Adding-Names-Teams-Colors}
driver_names_unique <- driver_names %>%
  select(driver_number, name_acronym, full_name, team_name, team_colour) %>%
  distinct(driver_number, .keep_all = TRUE)

# Now join safely
pitstop_averages <- pitstop_averages %>%
  left_join(driver_names_unique, by = "driver_number")
```

```{r Fixed-Color-Codes}
pitstop_averages <- pitstop_averages %>%
  mutate(team_colour = paste0("#", team_colour))
```

  ```{r Pitstop_Averages-Visualizations}
# I am going to create a visualization which creates a bar graph, but orders them from slowest to fastest
# Filter out drivers with missing team colors
pitstop_averages <- pitstop_averages %>%
  filter(!is.na(team_colour) & team_colour != "#NA")

ggplot(data = pitstop_averages, aes(x = reorder(name_acronym, average_pitstop_time),
                    y = average_pitstop_time,
                    fill = team_colour)) +
  geom_col() +
  scale_fill_identity() +
  labs(title = "Average Pitstop Times by Driver",
       x = "Driver",
       y = "Average Pitstop Time (seconds)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r Downloading the graph}
ggsave("pitstop_averages_graph.png", 
  width = 12, height = 8, 
  dpi = 900, 
  units = "in")
```

